version: '3.8'
services:
  instacart_postgres:
    image: postgres:15-alpine
    container_name: instacart_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: instacart_db
    ports:
      - "5434:5432"
    volumes:
      - instacart_data:/var/lib/postgresql/data

volumes:
  instacart_data:
